name: Testi
favicon: null
layout_spectrum: 0.57268
typography_spectrum: 0.5894
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3b3b3b'
    - '#efc676'
    - '#645f4d'
    - '#101010'
    - '#c3853b'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
