name: Testi
favicon: null
layout_spectrum: 0.9633278553374112
typography_spectrum: 0.8414898468181491
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
